---
- name: Centreon
  hosts: centreon-web
  remote_user: root
  roles:
    - "roles/common"
    - role: "roles/mariadb-server"
      mysql_root_password: "centreon"
    - role: "roles/centreon-web"
      php_timezone: "Europe/Paris"
      mysql_hostname: "localhost"
      mysql_port: "3306"
      mysql_root_password: "centreon"
      mysql_centreon_db: "centreon"
      mysql_centstorage_db: "centreon_storage"
      mysql_centreon_username: "centreon"
      mysql_centreon_password: "centreon"
      centreon_admin_password: "centreon"
      plugin_pack:
        - "base-generic"
        - "Linux SNMP"